services:
  - type: web
    name: newsflow-backend
    env: docker
    plan: free
    branch: main
    dockerfilePath: backend/Dockerfile
    dockerContext: backend
    healthCheckPath: /api/health
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: CORS_ORIGINS
        value: https://newsflow-three.vercel.app,https://newsflow-orcin.vercel.app
      - key: DATABASE_URL
        value: 'sqlite:///./newsflow.db'
